default_language_version:
  python: python3

exclude: (__init__.py|^enterprise|^server|^smile-addons|^extra-addons)

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--settings=."]
        exclude: __init__.py
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-print, flake8-debugger, flake8-blind-except, flake8-builtins, flake8-cognitive-complexity, flake8-comprehensions, flake8-deprecated, flake8-eradicate]
        args:
          [
            "--enable=T",
            "--max-line-length=120",
            "--select=E,W,F",
            "--ignore=W503,W504",
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: debug-statements
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
        exclude: (.md|.rst)
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        args: ["--write"]
        files: \.(js|css|scss|json)$
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
